- name: Download Erlang rpm
  get_url:
    url: http://packages.erlang-solutions.com/erlang-solutions-1.0-1.noarch.rpm
    dest: erlang.rpm      
- name: Install Erlang
  yum:
   name: erlang.rpm 
   state: present

- name: Base setup
  package: 
    name: "{{ item }}"
    state: present
  with_items:

  - "{{install_item}}"

  