- name: Download Erlang rpm
  get_url:
    url: http://packages.erlang-solutions.com/erlang-solutions-1.0-1.noarch.rpm
    dest: /tmp/erlang.rpm      
- name: Rpm add Erlang
  yum:
   install: /tmp/erlang.rpm
  

- name: Base setup
  package: 
    name: "{{ item }}"
    state: present
  with_items:

  - "{{install_item}}"
  - erlang

  