- name: Download Erlang rpm
  get_url:
    url: http://packages.erlang-solutions.com/erlang-solutions-1.0-1.noarch.rpm
    dest: /tmp/erlang.rpm      
- name: Rpm add Erlang
  shell: yum install /tmp/erlang.rpm -y

- name: Base setup
  package: 
    name: "{{ item }}"
    state: present
  with_items:
  - apt-transport-https
  - vim
  - curl
  - whois
  - telnet 
  - smartmontools
  - htop
  - bash-completion 
  - git
  - strace
  - screen
  - ntpdate 
  - software-properties-common
  - bzip2
  - net-tools
  - sudo
  - ntp
  - erlang
  - epel-release

  