
- name: Add rabbit repo
  shell: wget https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.4/rabbitmq-server-3.8.4-1.el8.noarch.rpm
  tags: 
  - deploy

- name: Add trusted key
  shell: rpm --import https://www.rabbitmq.com/rabbitmq-signing-key-public.asc
  tags: 
  - deploy

- name: Install rabbitmq
  yum:
   name: rabbitmq-server-3.8.4-1.el8.noarch.rpm
   state: present
  tags: 
  - deploy

- name: Enable rabbitmq plugins
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  notify:
    - restart rabbitmq
  tags: 
  - deploy

- name: Add rabbitmq users admin
  rabbitmq_user:
    user: "{{ item.username }}"
    password: "{{ item.username }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  with_items:
  - { username: "{{username}}", password: "{{userpassword}}"}
  tags: 
  - deploy
  - new-user

- name: Setup queue
  rabbitmq_queue:
    name: "{{item.queuename}}"
    login_host: 127.0.0.1
    login_user: "{{item.username}}"
    login_password: "{{item.password}}"
    login_port: "{{item.port}}"
  with_items:
  - { queuename: "{{qname}}", qusername: "{{qusername}}", qpassword: "{{qpass}}", qport: "{{qport}}"}
  tags: 
  - deploy
  - new-queue

- name: Remove the default user
  rabbitmq_user: 
    name: guest 
    state: absent
  tags: deploy
    